ExcludeArch: %{ix86}
# Generated by rust2rpm 26
%bcond_without check


%global commit ###
%global shortcommit %{sub %{commit} 1 7}
%global commitdatestring ###
%global commitdate ###

Name:           cosmic-ext-applet-external-monitor-brightness
Version: ###
Release:        %autorelease
Summary:        External Monitor Brightness Applet for COSMIC

SourceLicense:  GPL-3.0
License:        GPL-3.0

URL:            https://github.com/maciekk64/cosmic-ext-applet-external-monitor-brightness.git
	
Source0:        https://github.com/maciekk64/%{name}/archive/%{commit}/%{name}-%{shortcommit}.tar.gz
Source1:        vendor-%{shortcommit}.tar.gz
Source2:        vendor-config-%{shortcommit}.toml

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  just
BuildRequires:  libxkbcommon-devel
BuildRequires:  git-core
BuildRequires:  systemd-devel

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{name}-%{commit} -p1 -a1
%cargo_prep -N
# Check if .cargo/config.toml exists
if [ -f .cargo/config.toml ]; then
  # If it exists, append the contents of %%{SOURCE2} to .cargo/config.toml
  cat %{SOURCE2} >> .cargo/config.toml
  echo "Appended %{SOURCE2} to .cargo/config.toml"
else
  # If it does not exist, append the contents of %%{SOURCE2} to .cargo/config
  cat %{SOURCE2} >> .cargo/config
  echo "Appended %{SOURCE2} to .cargo/config"
fi

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}
sed 's/\(.*\) (.*#\(.*\))/\1+git\2/' -i cargo-vendor.txt

%install
just rootdir=%{buildroot} prefix=%{_prefix} install
%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/%{name}
%{_datadir}/applications/io.github.maciekk64.CosmicExtAppletExternalMonitorBrightness.desktop

%changelog
%autochangelog
