ExcludeArch: %{ix86}
# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

%global crate cosmic-ext-applet-external-monitor-brightness

%global ver ###
%global commit ###
%global date ###

Name:           cosmic-ext-applet-external-monitor-brightness
Version:        %{ver}~git%{date}.%{sub %{commit} 1 7}
Release:        %autorelease
Summary:        External Monitor Brightness Applet for COSMIC

SourceLicense:  GPL-3.0
License:        GPL-3.0

URL:            https://github.com/maciekk64/cosmic-ext-applet-external-monitor-brightness.git
	
Source:         %{crate}-%{commit}.tar.xz
Source:         %{crate}-%{commit}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  just
BuildRequires:  libxkbcommon-devel
BuildRequires:  git-core
BuildRequires:  systemd-devel

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{commit} -p1 -a1
%cargo_prep -N
# Check if .cargo/config.toml exists
if [ -f .cargo/config.toml ]; then
  # If it exists, append the contents of .vendor/config.toml to .cargo/config.toml
  cat .vendor/config.toml >> .cargo/config.toml
  echo "Appended .vendor/config.toml to .cargo/config.toml"
else
  # If it does not exist, append the contents of .vendor/config.toml to .cargo/config
  cat .vendor/config.toml >> .cargo/config
  echo "Appended .vendor/config.toml to .cargo/config"
fi

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}
sed 's/\(.*\) (.*#\(.*\))/\1+git\2/' -i cargo-vendor.txt

%install
just rootdir=%{buildroot} prefix=%{_prefix} install
%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/%{crate}
%{_datadir}/applications/io.github.maciekk64.CosmicExtAppletExternalMonitorBrightness.desktop

%changelog
%autochangelog
